AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
